/**
 * BlurChat - Privacy for WhatsApp Web
 * Popup Script
 * 🔐 Jaikant Shikre: SECURE License System + 🎨 Gabbar UIwala: UI interactions
 * 
 * LICENSE KEY FORMAT: BCPRO-XXXX-XXXX-XXXX
 * Each key is unique and validated using a checksum algorithm
 * Keys can be generated by the developer for each customer
 */

(function () {
    'use strict';

    // ==========================
    // DOM Elements
    // ==========================
    const elements = {
        // Toggles
        toggleMessages: document.getElementById('toggleMessages'),
        toggleNames: document.getElementById('toggleNames'),
        togglePhotos: document.getElementById('togglePhotos'),

        // Lock icons
        lockNames: document.getElementById('lockNames'),
        lockPhotos: document.getElementById('lockPhotos'),

        // License section
        licenseSection: document.getElementById('licenseSection'),
        licenseLocked: document.getElementById('licenseLocked'),
        licenseUnlocked: document.getElementById('licenseUnlocked'),
        licenseInput: document.getElementById('licenseInput'),
        verifyBtn: document.getElementById('verifyBtn'),
        licenseError: document.getElementById('licenseError'),
        resetLicenseBtn: document.getElementById('resetLicenseBtn'),
        upgradeLink: document.getElementById('upgradeLink'),

        // Pro section
        proSection: document.querySelector('.pro-section'),

        // Status
        statusIndicator: document.getElementById('statusIndicator')
    };

    // ==========================
    // SECURE LICENSE VALIDATION SYSTEM
    // ==========================

    /**
     * License Key Format: BCPRO-XXXX-XXXX-XXXX
     * - BCPRO = Fixed prefix
     * - First XXXX = Random alphanumeric (part1)
     * - Second XXXX = Random alphanumeric (part2)
     * - Third XXXX = Checksum of part1+part2 using secret salt
     * 
     * SECURITY: The salt is secret and embedded in the code.
     * Even if someone sees the validation logic, they need the salt to generate valid keys.
     * Change the salt below to create your own unique key system!
     */

    const SECRET_SALT = 'BC@2025#Pr1v4cy$K3y!'; // 🔐 CHANGE THIS to your own secret!

    // Generate checksum hash from string
    function generateChecksum(str) {
        let hash = 5381;
        const combined = str + SECRET_SALT;

        for (let i = 0; i < combined.length; i++) {
            const char = combined.charCodeAt(i);
            hash = ((hash << 5) + hash) ^ char;
        }

        // Convert to base36 (alphanumeric) and take last 4 chars
        const result = Math.abs(hash).toString(36).toUpperCase();
        return result.slice(-4).padStart(4, 'X');
    }

    // Validate license key format and checksum
    function validateLicenseKey(key) {
        // Normalize: uppercase, remove spaces
        const normalized = key.trim().toUpperCase().replace(/[\s-]/g, '');

        // Should be exactly 17 chars after removing dashes: BCPRO (5) + XXXX (4) + XXXX (4) + XXXX (4) = 17
        if (normalized.length !== 17) {
            return { valid: false, error: 'Invalid key format' };
        }

        // Check prefix
        if (!normalized.startsWith('BCPRO')) {
            return { valid: false, error: 'Invalid key format' };
        }

        // Extract parts (after BCPRO prefix)
        const dataSection = normalized.slice(5); // 12 chars: XXXX XXXX XXXX
        const part1 = dataSection.slice(0, 4);
        const part2 = dataSection.slice(4, 8);
        const providedChecksum = dataSection.slice(8, 12);

        // Calculate expected checksum
        const expectedChecksum = generateChecksum(part1 + part2);

        // Validate
        if (providedChecksum !== expectedChecksum) {
            return { valid: false, error: 'Invalid license key' };
        }

        // Format nicely for storage
        const formattedKey = `BCPRO-${part1}-${part2}-${providedChecksum}`;
        return { valid: true, key: formattedKey };
    }

    /**
     * 🔑 KEY GENERATOR - FOR DEVELOPER USE ONLY!
     * 
     * Open the extension popup, then open browser console (F12)
     * Run: generateBlurChatKey()
     * 
     * Each call generates a unique, cryptographically valid key.
     * Give one key per customer purchase.
     */
    function generateLicenseKey() {
        const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; // Removed confusing chars: 0,O,1,I
        let part1 = '';
        let part2 = '';

        for (let i = 0; i < 4; i++) {
            part1 += chars.charAt(Math.floor(Math.random() * chars.length));
            part2 += chars.charAt(Math.floor(Math.random() * chars.length));
        }

        const checksum = generateChecksum(part1 + part2);
        const key = `BCPRO-${part1}-${part2}-${checksum}`;

        console.log('%c🔑 NEW LICENSE KEY GENERATED:', 'color: #00a884; font-weight: bold; font-size: 14px;');
        console.log('%c' + key, 'color: #ffd700; font-weight: bold; font-size: 18px; background: #1f2c34; padding: 8px 16px; border-radius: 4px;');
        console.log('%cGive this key to your customer!', 'color: #8696a0; font-style: italic;');

        return key;
    }

    // Expose generator to console for developer
    window.generateBlurChatKey = generateLicenseKey;

    // ==========================
    // Constants
    // ==========================
    const UPGRADE_URL = 'https://gumroad.com/l/blurchat-pro'; // Update with your actual Gumroad link

    // ==========================
    // State Management
    // ==========================
    let state = {
        blurMessages: true,
        blurNames: false,
        blurPhotos: false,
        isPro: false,
        licenseKey: null
    };

    // Load state from storage
    async function loadState() {
        return new Promise((resolve) => {
            chrome.storage.local.get(['blurMessages', 'blurNames', 'blurPhotos', 'isPro', 'licenseKey'], (result) => {
                state = {
                    blurMessages: result.blurMessages !== undefined ? result.blurMessages : true,
                    blurNames: result.blurNames !== undefined ? result.blurNames : false,
                    blurPhotos: result.blurPhotos !== undefined ? result.blurPhotos : false,
                    isPro: result.isPro !== undefined ? result.isPro : false,
                    licenseKey: result.licenseKey || null
                };
                resolve(state);
            });
        });
    }

    // Save state to storage
    async function saveState(updates) {
        return new Promise((resolve) => {
            chrome.storage.local.set(updates, () => {
                Object.assign(state, updates);
                resolve();
            });
        });
    }

    // ==========================
    // UI Updates
    // ==========================
    function updateUI() {
        // Update toggle states
        elements.toggleMessages.checked = state.blurMessages;
        elements.toggleNames.checked = state.blurNames;
        elements.togglePhotos.checked = state.blurPhotos;

        // Update pro features availability
        if (state.isPro) {
            // Unlock pro features
            elements.toggleNames.disabled = false;
            elements.togglePhotos.disabled = false;
            elements.lockNames.textContent = '✓';
            elements.lockNames.style.color = '#21c063';
            elements.lockPhotos.textContent = '✓';
            elements.lockPhotos.style.color = '#21c063';

            // Show unlocked license section
            elements.licenseLocked.classList.add('hidden');
            elements.licenseUnlocked.classList.remove('hidden');

            // Update pro section style
            elements.proSection.classList.add('unlocked');
        } else {
            // Lock pro features
            elements.toggleNames.disabled = true;
            elements.togglePhotos.disabled = true;
            elements.toggleNames.checked = false;
            elements.togglePhotos.checked = false;
            elements.lockNames.textContent = '🔒';
            elements.lockNames.style.color = '';
            elements.lockPhotos.textContent = '🔒';
            elements.lockPhotos.style.color = '';

            // Show locked license section
            elements.licenseLocked.classList.remove('hidden');
            elements.licenseUnlocked.classList.add('hidden');

            // Update pro section style
            elements.proSection.classList.remove('unlocked');
        }

        // Clear any error messages
        elements.licenseError.textContent = '';
    }

    // ==========================
    // Message sending to content script
    // ==========================
    async function notifyContentScript() {
        try {
            // Get active WhatsApp tabs
            const tabs = await chrome.tabs.query({ url: 'https://web.whatsapp.com/*' });

            for (const tab of tabs) {
                try {
                    await chrome.tabs.sendMessage(tab.id, {
                        type: 'BC_SET_STATE',
                        payload: {
                            blurMessages: state.blurMessages,
                            blurNames: state.isPro ? state.blurNames : false,
                            blurPhotos: state.isPro ? state.blurPhotos : false,
                            isPro: state.isPro
                        }
                    });
                } catch (err) {
                    // Tab might not have content script loaded
                    console.log('Could not send to tab:', tab.id);
                }
            }
        } catch (err) {
            console.error('Error notifying content script:', err);
        }
    }

    // ==========================
    // Event Handlers
    // ==========================

    // Toggle message blur (free tier)
    elements.toggleMessages.addEventListener('change', async (e) => {
        await saveState({ blurMessages: e.target.checked });
        await notifyContentScript();
    });

    // Toggle name blur (pro tier)
    elements.toggleNames.addEventListener('change', async (e) => {
        if (!state.isPro) {
            e.target.checked = false;
            showError('Unlock Pro to use this feature');
            return;
        }
        await saveState({ blurNames: e.target.checked });
        await notifyContentScript();
    });

    // Toggle photo blur (pro tier)
    elements.togglePhotos.addEventListener('change', async (e) => {
        if (!state.isPro) {
            e.target.checked = false;
            showError('Unlock Pro to use this feature');
            return;
        }
        await saveState({ blurPhotos: e.target.checked });
        await notifyContentScript();
    });

    // Verify license button - NOW USES SECURE VALIDATION
    elements.verifyBtn.addEventListener('click', async () => {
        const inputKey = elements.licenseInput.value.trim();

        if (!inputKey) {
            showError('Please enter a license key');
            shakeElement(elements.licenseInput);
            return;
        }

        // Validate using secure checksum algorithm
        const result = validateLicenseKey(inputKey);

        if (result.valid) {
            // Valid key!
            await saveState({ isPro: true, licenseKey: result.key });
            updateUI();
            await notifyContentScript();

            // Show success feedback
            elements.licenseInput.value = '';
            showSuccess('Pro License Activated! 🎉');

            console.log('[BlurChat] License activated:', result.key);
        } else {
            // Invalid key
            showError(result.error || 'Invalid license key');
            shakeElement(elements.licenseInput);
        }
    });

    // Enter key on license input
    elements.licenseInput.addEventListener('keypress', (e) => {
        if (e.key === 'Enter') {
            elements.verifyBtn.click();
        }
    });

    // Reset license button
    elements.resetLicenseBtn.addEventListener('click', async () => {
        if (confirm('Are you sure you want to reset your Pro license?')) {
            await saveState({
                isPro: false,
                licenseKey: null,
                blurNames: false,
                blurPhotos: false
            });
            updateUI();
            await notifyContentScript();
        }
    });

    // Upgrade link
    elements.upgradeLink.addEventListener('click', (e) => {
        e.preventDefault();
        chrome.tabs.create({ url: UPGRADE_URL });
    });

    // ==========================
    // Helper Functions
    // ==========================
    function showError(message) {
        elements.licenseError.textContent = message;
        elements.licenseError.style.color = '#f15c6d';
    }

    function showSuccess(message) {
        elements.licenseError.textContent = message;
        elements.licenseError.style.color = '#21c063';
        setTimeout(() => {
            elements.licenseError.textContent = '';
        }, 3000);
    }

    function shakeElement(element) {
        element.classList.add('shake');
        setTimeout(() => {
            element.classList.remove('shake');
        }, 300);
    }

    // ==========================
    // Initialization
    // ==========================
    async function init() {
        await loadState();
        updateUI();
        console.log('[BlurChat Popup] Initialized with state:', state);
        console.log('%c💡 Developer: Run generateBlurChatKey() to create license keys!', 'color: #00a884;');
    }

    // Start
    init();

})();
